# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eaa06cd9862eb305468059993cb702c2"
application_url = "https://treated-prostate-contest-terry.trycloudflare.com"
embedded = true
name = "Delivery Customizations API"
handle = "delivery-customizations-filter"

[build]
include_config_on_deploy = true
dev_store_url = "kieransteststore1.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations"

[auth]
redirect_urls = [
  "https://treated-prostate-contest-terry.trycloudflare.com/auth/callback",
  "https://treated-prostate-contest-terry.trycloudflare.com/auth/shopify/callback",
  "https://treated-prostate-contest-terry.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
